plugins:
- jekyll-seo-tag
- jekyll-polyglot

languages: ["en"]
default_lang: "en"
exclude_from_localization: ["assets/css", "images"]
parallel_localization: true

sass:
  sourcemap: never

markdown: kramdown

google_analytics: G-13GTE0C2R4

title: Infinitespace Studios
description: Mobile and Game Development

exclude:
  - README.md
  - "*.code-workspace"

include:
  - images
  - assets/games/co-operoids/_framework