plugins:
- jekyll-seo-tag

markdown: kramdown

google_analytics: G-13GTE0C2R4

title: Infinitespace Studios
description: Mobile and Game Development

exclude:
  - README.md
  - "*.code-workspace"

include:
  - images